apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    app: alertmanager
  name: example
  namespace: monitoring
spec:
  baseImage: quay.io/prometheus/alertmanager
  externalUrl: https://alertmanager$(WILDCARD_INGRESS_DNS)
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  portName: web
  replicas: 1
  retention: 120h
  routePrefix: /
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-account
  version: v0.21.0
#  alertmanagerConfigSelector:
#      matchLabels:
#        alertmanagerConfig: alertmanager-config
