global:
  resolve_timeout: 5m
  smtp_from: "AKS Platform-DEVQA Alerts<aks-qa-alertmanager@sephora.com>"
  smtp_smarthost: azre1-smtp-lower.sephoraus.com:25
  smtp_require_tls: false
route:
  receiver: "null"
receivers:
- name: "null"
templates:
- '/etc/alertmanager/config/seph-email.tmpl'
