resources:
- ../prometheus-base/prometheus-operator
- ./plat-alertmanager-config.yml
- ./alertmanager-plat.yml
patchesStrategicMerge:
- ./prometheus-operator.yml
secretGenerator:
- name: alertmanager-prometheus-operator-alertmanager
  files:
  - ./seph-email.tmpl
  - ./alertmanager.yaml
