resources:
- ../prometheus-base/prometheus-operator
- ./plat-alertmanager-config.yml
patchesStrategicMerge:
- ./prometheus-operator.yml
secretGenerator:
- name: alertmanager-config
  files:
  - ./alertmanager.yaml
  - ./seph-email.tmpl
