resources:
- ../prometheus-base/prometheus-operator
- ./plat-alertmanager-config.yml
- ./alertmanager-plat.yml
- ./alertmanager.yaml
patchesStrategicMerge:
- ./prometheus-operator.yml
secretGenerator:
- name: alertmanager-test
  files:
  - ./seph-email.tmpl
