resources:
- ../prometheus-base/prometheus-operator
- ./plat-alertmanager-config.yml
patchesStrategicMerge:
- ./prometheus-operator.yml
secretGenerator:
- name: alertmanager-email
  files:
  - ./seph-email.tmpl
