resources:
- ../prometheus-base/prometheus-operator
- ./alertmanager-rbac.yml
- ./plat-alertmanager-config.yml
- ./alertmanager-plat.yml
patchesStrategicMerge:
- ./prometheus-operator.yml
secretGenerator:
- name: alertmanager-examples
  files:
  - ./seph-email.tmpl
  - ./alertmanager.yaml
generatorOptions:
  disableNameSuffixHash: true
