resources:
- ../prometheus-base/prometheus-operator
- ./alertmanager-rbac.yml
#- ./plat-alertmanager-config.yml
- ./alertmanager-plat.yml
patchesStrategicMerge:
- ./prometheus-operator.yml
secretGenerator:
- name: alertmanager-example
  files:
  - ./seph-email.tmpl
  - ./alertmanager.yaml
