apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
  labels:
    scope: system
spec:
  source:
    helm:
      parameters:
        - name: "app"
          value: $ARGOCD_APP_NAME
        - name: prometheus.prometheusSpec.replicas
          value: '1'
        - name: prometheus.prometheusSpec.resources.requests.cpu
          value: '300m'
        - name: prometheus.prometheusSpec.resources.requests.memory
          value: '500Mi'
        - name: prometheus.prometheusSpec.resources.limits.cpu
          value: '300m'
        - name: prometheus.prometheusSpec.resources.limits.memory
          value: '1Gi'
